# Generated by Django 3.1.3 on 2021-01-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('bookName', models.CharField(max_length=30)),
                ('bookWriter', models.CharField(max_length=40)),
                ('release_date', models.DateField()),
                ('price', models.IntegerField()),
                ('bookCategory', models.CharField(max_length=50)),
                ('bookImage', models.ImageField(blank='false', upload_to='book/images/')),
            ],
        ),
    ]
